### ISSUE TITLE
Some of the sample project deployments are failing

### ISSUE THREAD

**Issue by Yonet** [microsoft/static-web-apps-gallery-code-samples#27]
Below projects demo sites error: 
- xLayers demo
- Angular AppStore demo
- Angular AppStore demo
- Meme4Fun project

We can update them or remove them from the samples.

**Comment by simonaco** [comment]
@manekinekko would you mind updating the links to xLayers and angular appstore demo?

**Comment by fhinkel** [comment]
We deleted the outdated links.
